### ISSUE TITLE
Homoginize kmod-*-nvidia spec files

### ISSUE THREAD

**Issue by arnaldo2792** [bottlerocket-os/bottlerocket-core-kit#115]
**What I'd like:**
When we introduced support for NVIDIA, we wrote the spec file for kmod-5.10-nvidia spec thinking that we will support different driver versions at once for a given kernel. We changed opinions, and we decided to ship only one driver version per kernel and that's what we followed for `kmod-5.15-nvidia` and `kmod-6.1-nvidia`. We should fix the `kmod-5.10-nvidia` spec to follow what we did in `kmod-5.15-nvidia` and `kmod-6.1-nvidia`, and simplify how the driver is installed

**Any alternatives you've considered:**
Keep using the versioned schema in the `kmod-5.10-nvidia` spec file, but it id hard for downstream users to consume some of the artifacts generated in the spec file since the version is injected in [some of them](https://github.com/bottlerocket-os/bottlerocket-core-kit/blob/59de30b0a342c63e9f7ea0a841e8869897959ea8/packages/kmod-5.10-nvidia/kmod-5.10-nvidia.spec#L115). It will be easier to have the only path without the version to find NVIDIA's binaries, and it will simplify by a lot the spec file.

**Comment by bcressey** [comment]
Done in #181.
