### ISSUE TITLE
`make twoliter check-clippy` failing with update to bottlerocket-sdk v0.46.0

### ISSUE THREAD

**Issue by ginglis13** [bottlerocket-os/bottlerocket-core-kit#192]
bottlerocket-sdk v0.46.0 includes a bump of the rust toolchain to 1.81.0: https://github.com/bottlerocket-os/bottlerocket-sdk/pull/204. Running `make twoliter check-clippy` in the core kit with this SDK fail. This ticket will track either directly addressing those lints or defining a clippy configuration for this repository. Re-enable the `make twoliter check-clippy` step in CI once complete.

**Comment by bcressey** [comment]
Fixed in #191.
